// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
#include "precomp.h"
#include "common.h"
#include "ProcessMonitor.h"

#define MAX_RESERVED_PORT 1024
// Upper bound (exclusive) for the unprivileged vsock port scan. The port is
// bound by an unprivileged user-distro process (mutter), so it cannot live in
// the reserved range WSLGd itself could have used.
#define MAX_UNPRIVILEGED_SCAN_PORT 4096

constexpr auto c_serviceIdTemplate = "%08X-FACB-11E6-BD58-64006A7986D3";
constexpr auto c_userName = "wslg";

constexpr auto c_dbusDir = "/var/run/dbus";
constexpr auto c_versionFile = "/etc/versions.txt";
constexpr auto c_versionMount = SHARE_PATH "/versions.txt";
constexpr auto c_shareDocsDir = "/usr/share/doc";
constexpr auto c_shareDocsMount = SHARE_PATH "/doc";
constexpr auto c_x11RuntimeDir = SHARE_PATH "/.X11-unix";
constexpr auto c_xdgRuntimeDir = SHARE_PATH "/runtime-dir";
constexpr auto c_stdErrLogFile = SHARE_PATH "/stderr.log";

constexpr auto c_sharedMemoryMountPoint = "/mnt/shared_memory";
constexpr auto c_sharedMemoryMountPointEnv = "WSL2_SHARED_MEMORY_MOUNT_POINT";
constexpr auto c_sharedMemoryObDirectoryPathEnv = "WSL2_SHARED_MEMORY_OB_DIRECTORY";

// WSLGd does not launch a compositor or an RDP client. It publishes the RDP
// transport info to a shell-sourceable env file in the shared /mnt/wslg mount.
// A launcher in the user distro (see run-vsock.sh) sources this file, starts its
// own mutter bound to the published vsock port, and starts the RDP client
// itself. Neither mutter nor the RDP client is baked into the system image.
constexpr auto c_mutterEnvFile = SHARE_PATH "/mutter-rdp.env";

// The virtiofs tag WSLGd uses for the shared-memory DAX share. It is VM-wide, so
// the user distro can mount the same share independently. WSLGd's own mount
// point (/mnt/shared_memory) only exists in the system-distro mount namespace,
// so the user-distro launcher cannot reuse that path; it mounts the share
// itself using this tag.
constexpr auto c_sharedMemoryVirtioTag = "wslg";

void LogPrint(int level, const char *func, int line, const char *fmt, ...) noexcept
{
    std::array<char, 128> buffer;
    struct timeval tv;
    struct tm *time;
    va_list va_args;

    gettimeofday(&tv, NULL);
    time = localtime(&tv.tv_sec);
    strftime(buffer.data(), buffer.size(), "%H:%M:%S", time);
    fprintf(stderr, "[%s.%03ld] <%d>WSLGd: %s:%u: ",
        buffer.data(), (tv.tv_usec / 1000),
        level, func, line);

    va_start(va_args, fmt);
    vfprintf(stderr, fmt, va_args);
    va_end(va_args);
    fprintf(stderr, "\n");

    return;
}

void LogException(const char *message, const char *exceptionDescription) noexcept
{
    LogPrint(LOG_LEVEL_EXCEPTION, __FUNCTION__, __LINE__, "%s %s", message ? message : "Exception:", exceptionDescription);
    return;
}

std::string ToServiceId(unsigned int port)
{
    int size;
    THROW_LAST_ERROR_IF((size = snprintf(nullptr, 0, c_serviceIdTemplate, port)) < 0);

    std::string serviceId(size + 1, '\0');
    THROW_LAST_ERROR_IF(snprintf(&serviceId[0], serviceId.size(), c_serviceIdTemplate, port) < 0);

    return serviceId;
}

// Publish the RDP transport info to a shell-sourceable env file in the shared
// mount. Written to a temp file then renamed so a reader never observes a
// partial file. A user-distro launcher (run-vsock.sh) sources this file to learn
// the vsock port to bind, the hvsocket service id the RDP client must connect
// to, and the shared memory the compositor may use. This file is data only: it
// does not exec anything and imposes no library paths, so the launcher is free
// to run its own mutter build and its own RDP client.
void WriteMutterEnvFile(
    const char *path,
    const std::string &vmId,
    unsigned int port,
    const std::string &serviceId,
    bool isSharedMemoryMounted,
    const char *sharedMemoryObDirectoryPath)
{
    std::string tmpPath(path);
    tmpPath += ".tmp";

    std::string contents;
    contents += "# Generated by WSLGd. Source this from the user distro to learn the\n";
    contents += "# WSLg RDP transport for a self-launched mutter compositor.\n";
    contents += "MUTTER_RDP_VSOCK_PORT=";
    contents += std::to_string(port);
    contents += "\n";
    // The Hyper-V VM GUID (hvsocket address) the RDP client must connect to,
    // i.e. mstsc/msrdc's /v: argument.
    contents += "WSLG_VM_ID=";
    contents += vmId;
    contents += "\n";
    // The hvsocket service id (a GUID derived from the vsock port) that the RDP
    // client on the Windows side must be pointed at.
    contents += "WSLG_SERVICE_ID=";
    contents += serviceId;
    contents += "\n";
    if (isSharedMemoryMounted) {
        // WSLGd's /mnt/shared_memory lives in the system-distro mount namespace,
        // so the launcher must mount the same VM-wide virtiofs DAX share itself
        // (by tag) at a path of its choosing in the user distro.
        contents += "WSLG_SHARED_MEMORY_VIRTIO_TAG=";
        contents += c_sharedMemoryVirtioTag;
        contents += "\n";
        // The NT object directory backing that share, as handed to WSLGd by the
        // WSL service. The RDP client needs it (/wslgsharedmemorypath:) to map
        // the same memory from the Windows side.
        if (sharedMemoryObDirectoryPath) {
            contents += "WSLG_SHARED_MEMORY_OB_DIRECTORY='";
            contents += sharedMemoryObDirectoryPath;
            contents += "'\n";
        }
    }

    wil::unique_fd fd{open(tmpPath.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0644)};
    THROW_LAST_ERROR_IF(!fd);

    THROW_LAST_ERROR_IF(write(fd.get(), contents.c_str(), contents.size()) != static_cast<ssize_t>(contents.size()));
    fd.reset();

    THROW_LAST_ERROR_IF(rename(tmpPath.c_str(), path) < 0);
}

bool GetEnvBool(const char *EnvName, bool DefaultValue)
{
    char *s;

    s = getenv(EnvName);
    if (s) {
        if (strcmp(s, "true") == 0)
            return true;
        else if (strcmp(s, "false") == 0)
            return false;
        else if (strcmp(s, "1") == 0)
            return true;
        else if (strcmp(s, "0") == 0)
            return false;
    }

    return DefaultValue;
}

std::string GetVmId()
{
    std::unique_ptr<FILE, decltype(&pclose)> pipe(popen("/usr/bin/wslinfo --vm-id -n", "r"), pclose);
    THROW_LAST_ERROR_IF(!pipe);

    std::array<char, 128> buffer;
    std::string result;
    while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
        result += buffer.data();
    }

    THROW_ERRNO_IF(EINVAL, pclose(pipe.release()) != 0);

    return result;
}

int main(int Argc, char *Argv[])
try {
    wil::g_LogExceptionCallback = LogException;

    // Restore default processing for SIGCHLD.
    signal(SIGCHLD, SIG_DFL);

    // Create a process monitor to track child processes
    wslgd::ProcessMonitor monitor(c_userName);
    auto passwordEntry = monitor.GetUserInfo();

    // Set required environment variables. These are inherited by the child
    // processes WSLGd launches (just dbus-daemon now); the compositor and
    // the RDP client run in the user distro and get their environment there.
    struct envVar{ const char* name; const char* value; bool override; };
    envVar variables[] = {
        {"HOME", passwordEntry->pw_dir, true},
        {"USER", passwordEntry->pw_name, true},
        {"LOGNAME", passwordEntry->pw_name, true},
        {"SHELL", passwordEntry->pw_shell, true},
        {"PATH", "/usr/sbin:/usr/bin:/sbin:/bin:/usr/games", true},
        {"XDG_RUNTIME_DIR", c_xdgRuntimeDir, false},
    };

    for (auto &var : variables) {
        THROW_LAST_ERROR_IF(setenv(var.name, var.value, var.override) < 0);
    }

    // if any components output log to /dev/kmsg, make it writable.
    if (GetEnvBool("WSLG_LOG_KMSG", false))
        THROW_LAST_ERROR_IF(chmod("/dev/kmsg", 0666) < 0);

    // Open a file for logging errors and set it to stderr for WSLGd as well as any child process.
    {
        const char *errLog = getenv("WSLG_ERR_LOG_PATH");
        if (!errLog) {
            errLog = c_stdErrLogFile;
        }
        wil::unique_fd stdErrLogFd(open(errLog, (O_RDWR | O_CREAT), (S_IRUSR | S_IRGRP | S_IROTH)));
        if (stdErrLogFd && (stdErrLogFd.get() != STDERR_FILENO)) {
            dup2(stdErrLogFd.get(), STDERR_FILENO);
        }
    }

    // Ensure the daemon is launched as root.
    if (geteuid() != 0) {
        LOG_ERROR("must be run as root.");
        return 1;
    }

    // Query the VM ID.
    auto vmId = GetVmId();
    if (vmId.empty()) {
        LOG_ERROR("could not query VM ID.");
        return 1;
    }

    // Bind mount the versions.txt file which contains version numbers of the various WSLG pieces.
    {
        wil::unique_fd fd(open(c_versionMount, (O_RDWR | O_CREAT), (S_IRUSR | S_IRGRP | S_IROTH)));
        THROW_LAST_ERROR_IF(!fd);
    }

    THROW_LAST_ERROR_IF(mount(c_versionFile, c_versionMount, NULL, MS_BIND | MS_RDONLY, NULL) < 0);

    std::filesystem::create_directories(c_shareDocsMount);
    THROW_LAST_ERROR_IF(mount(c_shareDocsDir, c_shareDocsMount, NULL, MS_BIND | MS_RDONLY, NULL) < 0);

    // Make directories and ensure the correct permissions.
    std::filesystem::create_directories(c_dbusDir);
    THROW_LAST_ERROR_IF(chown(c_dbusDir, passwordEntry->pw_uid, passwordEntry->pw_gid) < 0);
    THROW_LAST_ERROR_IF(chmod(c_dbusDir, 0777) < 0);

    // The user distro's Xwayland (started alongside mutter) creates its socket
    // here; WSL bind mounts this directory in as /tmp/.X11-unix.
    std::filesystem::create_directories(c_x11RuntimeDir);
    THROW_LAST_ERROR_IF(chmod(c_x11RuntimeDir, 0777) < 0);

    std::filesystem::create_directories(c_xdgRuntimeDir);
    THROW_LAST_ERROR_IF(chown(c_xdgRuntimeDir, passwordEntry->pw_uid, passwordEntry->pw_gid) < 0);
    THROW_LAST_ERROR_IF(chmod(c_xdgRuntimeDir, 0777) < 0);

    // Attempt to mount the virtiofs share for shared memory.
    bool isSharedMemoryMounted = false;
    auto sharedMemoryObDirectoryPath = getenv(c_sharedMemoryObDirectoryPathEnv);
    if (sharedMemoryObDirectoryPath) {
        std::filesystem::create_directories(c_sharedMemoryMountPoint);
        if (mount(c_sharedMemoryVirtioTag, c_sharedMemoryMountPoint, "virtiofs", 0, "dax") < 0) {
            LOG_ERROR("Failed to mount wslg shared memory %s.", strerror(errno));
        } else {
            THROW_LAST_ERROR_IF(chmod(c_sharedMemoryMountPoint, 0777) < 0);
            isSharedMemoryMounted = true;
        }
    } else {
        LOG_ERROR("shared memory ob directory path is not set.");
    }

    // Pick the vsock port to be used for the RDP connection and derive the
    // hvsocket service ID from it. The port is bound by the user-distro mutter,
    // which runs unprivileged and cannot bind a reserved port, so scan the
    // unprivileged range. WSLGd only probes for a free port here; it releases it
    // again immediately so mutter can bind it.
    sockaddr_vm address{};
    address.svm_family = AF_VSOCK;
    address.svm_cid = VMADDR_CID_ANY;
    socklen_t addressSize = sizeof(address);
    wil::unique_fd socketFd{socket(AF_VSOCK, SOCK_STREAM, 0)};
    THROW_LAST_ERROR_IF(!socketFd);
    bool boundPort = false;
    for (unsigned int port = MAX_RESERVED_PORT; port < MAX_UNPRIVILEGED_SCAN_PORT; port += 1) {
        address.svm_port = port;
        if (bind(socketFd.get(), reinterpret_cast<const sockaddr*>(&address), addressSize) == 0) {
            boundPort = true;
            break;
        }

        THROW_LAST_ERROR_IF(errno != EADDRINUSE);
    }

    THROW_ERRNO_IF(EINVAL, !boundPort);

    // N.B. ToServiceId() returns a string with a trailing embedded NUL; trim it
    // so the value is safe to embed in a text file.
    std::string serviceIdValue(ToServiceId(address.svm_port).c_str());

    // Release the port so the user-distro mutter can bind it, and publish the
    // transport info to the env file for the launcher to read. There is a brief
    // window where the port is unbound; mutter is expected to bind it promptly
    // and the scanned range is otherwise unused.
    socketFd.reset();
    WriteMutterEnvFile(
        c_mutterEnvFile,
        vmId,
        address.svm_port,
        serviceIdValue,
        isSharedMemoryMounted,
        sharedMemoryObDirectoryPath);
    LOG_INFO("published RDP vsock port %u (service id %s) to %s",
        address.svm_port, serviceIdValue.c_str(), c_mutterEnvFile);

    struct rlimit limit;
    THROW_LAST_ERROR_IF(getrlimit(RLIMIT_NOFILE, &limit) < 0);
    limit.rlim_cur = limit.rlim_max;
    THROW_LAST_ERROR_IF(setrlimit(RLIMIT_NOFILE, &limit) < 0);

    // Set shared memory mount point to env when available.
    if (!isSharedMemoryMounted ||
        (setenv(c_sharedMemoryMountPointEnv, c_sharedMemoryMountPoint, true) < 0)) {
        // shared memory is not available, env must be cleared if it's set.
        THROW_LAST_ERROR_IF(unsetenv(c_sharedMemoryMountPointEnv) < 0);
        isSharedMemoryMounted = false;
    }

    // Launch the system dbus daemon.
    monitor.LaunchProcess(std::vector<std::string>{
        "/usr/bin/dbus-daemon",
        "--syslog",
        "--nofork",
        "--nopidfile",
        "--system"
        },
        std::vector<cap_value_t>{CAP_SETGID, CAP_SETUID}
    );

    // Audio no longer runs through WSLGd: the RDP audio bridge connects
    // directly to a PipeWire instance in the user distro (see
    // mutter/src/backends/rdp/meta-rdp-audio.c), so there is nothing left for
    // WSLGd to launch here.

    return monitor.Run();
}
CATCH_RETURN_ERRNO();
