// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
#include <sys/capability.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/prctl.h>
#include <sys/mount.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <assert.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <algorithm>
#include <linux/vm_sockets.h>
#include <array>
#include <filesystem>
#include <map>
#include <memory>
#include <new>
#include <vector>
#include "lxwil.h"
